// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhZotmIUY9NR1pPrxRYdct2eyVdw6RBVA',
    appId: '1:965143620885:web:fb5a315d41547996ff0d1c',
    messagingSenderId: '965143620885',
    projectId: 'thandri-eb786',
    authDomain: 'thandri-eb786.firebaseapp.com',
    storageBucket: 'thandri-eb786.appspot.com',
    measurementId: 'G-5CP4T68NKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD_uJ7udrN47QU5VinjUH1sbCDUdAS9MU',
    appId: '1:965143620885:android:ca0192c431a073b2ff0d1c',
    messagingSenderId: '965143620885',
    projectId: 'thandri-eb786',
    storageBucket: 'thandri-eb786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuvav1hNXpKYlp3VmgIsqXq8tMO5aKxZQ',
    appId: '1:965143620885:ios:928ae986a4dc1527ff0d1c',
    messagingSenderId: '965143620885',
    projectId: 'thandri-eb786',
    storageBucket: 'thandri-eb786.appspot.com',
    iosBundleId: 'com.example.shalom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuvav1hNXpKYlp3VmgIsqXq8tMO5aKxZQ',
    appId: '1:965143620885:ios:98c4ce5f3bb95b42ff0d1c',
    messagingSenderId: '965143620885',
    projectId: 'thandri-eb786',
    storageBucket: 'thandri-eb786.appspot.com',
    iosBundleId: 'com.example.shalom.RunnerTests',
  );
}
